name: Deploy Ansible to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy LAMP
      run: |
        mkdir  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bc-lrs
        chmod 600 ~/.ssh/bc-lrs
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/bc-lrs root@45.79.130.177 'apt-get update && apt-get install -y apache2 mysql-server php libapache2-mod-php'
